[package]
name = "boring-util"
version = "0.1.0"
edition = "2024"

[dependencies]
boring = { git = "https://github.com/scraptors/boring", rev = "62b03ada7fcb2d4201ccdabca2028bb2fbe09943", features = ["pq-experimental"] }
brotli = "8.0.2"
flate2 = "1.1.2"
zstd = "0.13.3"
